server:
  port: 80
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://185.217.131.39:5432/event
    password: turgun1970
    username: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  main:
    lazy-initialization: true
  mvc:
    servlet:
      path: /api
jwt:
  secretKey: SupperKey
  expireTime: 864000000