server:
  port: 80
spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/event
    password: Aziz20034843
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  main:
    lazy-initialization: true
  mvc:
    servlet:
      path: /api
jwt:
  secretKey: SupperKey
  expireTime: 864000000